name: Sync MetriScan Backend to Hugging Face

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Sync backend to Hugging Face
        uses: huggingface/hub-sync@v0.3.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: Mohanbankuru/metriscan-backend
          hf_token: ${{ secrets.HF_TOKEN }}
          subdirectory: backend
          space_sdk: gradio
